using System;

namespace dotObfs.Core.C
{
    // Thanks to Microsoft Bing AI
    // for doing this hard work !
    public enum TokenType
    {
        Auto,
        Break,
        Case,
        Char,
        Const,
        Continue,
        Default,
        Do,
        Double,
        Else,
        Enum,
        Extern,
        Float,
        For,
        Goto,
        If,
        Int,
        Long,
        Register,
        Return,
        Short,
        Signed,
        Sizeof,
        Static,
        Struct,
        Switch,
        Typedef,
        Union,
        Unsigned,
        Void,
        Volatile,
        While,

        Text,
        Number,
        Character,

        LeftParenthesis,
        RightParenthesis,
        Plus,
        Minus,
        Star,
        Slash,
        Percent,
        Equal,
        ExclamationMark,
        And,
        Pipe,
        Xor,
        OpenAngleBracket,
        CloseAngleBracket,
        At,
        Hashtag,
        OpenBracket,
        CloseBracket,
        OpenCurlyBracket,
        CloseCurlyBracket,
        Backtick,
        SingleQuote,
        DoubleQuote,
        Tilde,
        Semicolon,
        Colon,
        Comma,
        Dot,
        Underscore,
        Backslash,
        QuestionMark,

        Identifier,
        WhiteSpace,
        EOF
    }
}
